name: CI/CD

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - 'feature/*'

jobs:
  build_dependencies:
    runs-on: ubuntu-latest
    name: Install Dependencies

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

  run_tests:
    needs: build_dependencies
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests
        run: npm test

  build_application:
    needs: run_tests
    runs-on: ubuntu-latest
    name: Build Application

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Application
        run: npm run build
