name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd frontend
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build --if-present
      - name: Run tests
        run: npm test