name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # Siehe unterstützten Veröffentlichungszeitplan von Node.js unter https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - run: cd frontend
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
